version: '3'
services:
  mail:
    build:
      context: ./mail
      dockerfile: Dockerfile
      args:
        fqdn: ${FQDN}
    container_name: mail
    ports:
      - "0.0.0.0:25:25"
      - "0.0.0.0:587:587"
      - "0.0.0.0:465:465"
      - "0.0.0.0:110:110"
      - "0.0.0.0:995:995"
    expose:
      - 993
      - 143
    cap_add:
      - NET_ADMIN
    extra_hosts:
      - "${FQDN}:127.0.0.1"
    hostname: ${FQDN}
    domainname: ${FQDN}

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        fqdn: ${FQDN}
        email: ${EMAIL}
    container_name: web
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    cap_add:
      - NET_ADMIN
    volumes:
      - ./web/www:/var/www
    environment:
      - DOMAIN=${FQDN}
      - EMAIL=${EMAIL}
      - LETSENCRYPT=${LETSENCRYPT}
    extra_hosts:
      - "${FQDN}:127.0.0.1"
    hostname: ${FQDN}

#  rainloop:
#    image: hardware/rainloop
#    container_name: rainloop
#    volumes:
#      - ./rainloop:/rainloop/data
#    depends_on:
#      - mail
#    ports:
#      - "127.0.0.1:8888:8888"
